# Question
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Answer

threshold = 10

lst = [1,2]

for i in range(threshold-2):
    print(lst[0])
    print(lst[1])
    sum_of_list = sum(lst)
    last_element = lst[-1]
    lst[0] = last_element
    lst[1] = sum_of_list
    print(sum_of_list)